CC      = gcc
CFLAGS  = -Wall -Wextra -O2 -std=c11
LIBS    = -lcrypto

TARGET  = rhc_adv_poc
SRCS    = rhc_adv.c main_adv.c

all: $(TARGET)

$(TARGET): $(SRCS) rhc_adv.h rhc_config.h
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS) $(LIBS)

clean_adv:
	rm -f $(TARGET)

run_adv: all
	./$(TARGET)

.PHONY: all clean_adv run_adv
